[project]
name = "ride-duration-batch"
version = "0.1.0"
description = "Batch scoring script for ride duration model"
requires-python = "==3.10.13"
dependencies = [
    "scikit-learn==1.5.0",
    "pandas",
    "pyarrow"
]
